# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/pylint
  rev: v2.17.5
  hooks:
  - id: pylint
    additional_dependencies:
    - aiohttp==3.7.3
    - bite-parser==0.2.2
    - dataclasses-serialization==1.3.1
    - prometheus_client==0.11
    - pytest==7.4.0
    - requests==2.26.0
    - uvicorn==0.15.0
    - xsdata==23.7
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    additional_dependencies: ["types-requests==2.28.11.12"]
