language: python
serices:
  - docker
python:
  - "3.7"
  - "3.8"
  - "3.9"
install: pip install poetry && poetry install
script: poetry run pytest --cov-report=xml --cov=dmarc_metrics_exporter && bash <(curl -s https://codecov.io/bash)
