[tool.poetry]
name = "dmarc-metrics-exporter"
version = "0.1.0"
description = "Export Prometheus metrics from DMARC reports."
authors = ["Jan Gosmann <jan@hyper-world.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
prometheus_client = "^0.9.0"
xsdata = "^20.12"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.2.1"
pylint = "^2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
