---
dmarc_metrics_exporter_version: ""

listen_addr: "127.0.0.1"
listen_port: 9797

imap_host: "localhost"
imap_port: 993
poll_interval_seconds: 60

folder_inbox: "INBOX"
folder_done: "Archive"
folder_error: "Invalid"
